-- MySQL Script generated by MySQL Workbench
-- Wed Feb 24 16:09:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `idClient` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `adresseMail` VARCHAR(255) NULL,
  `adresseLivraison` VARCHAR(255) NULL,
  `adresseFacturation` VARCHAR(255) NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commande` (
  `idCommande` INT NOT NULL,
  `ref` VARCHAR(45) NULL,
  `dateCreation` DATE NULL,
  `idClient` INT NOT NULL,
  PRIMARY KEY (`idCommande`, `idClient`),
  INDEX `fk_Commande_Client1_idx` (`idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Commande_Client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `mydb`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produit` (
  `idProduit` INT NOT NULL,
  `ref` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`idProduit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contenir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contenir` (
  `idCommande` INT NOT NULL,
  `idProduit` INT NOT NULL,
  PRIMARY KEY (`idCommande`, `idProduit`),
  INDEX `fk_Commande_has_Produit_Produit1_idx` (`idProduit` ASC) VISIBLE,
  INDEX `fk_Commande_has_Produit_Commande_idx` (`idCommande` ASC) VISIBLE,
  CONSTRAINT `fk_Commande_has_Produit_Commande`
    FOREIGN KEY (`idCommande`)
    REFERENCES `mydb`.`commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_has_Produit_Produit1`
    FOREIGN KEY (`idProduit`)
    REFERENCES `mydb`.`produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
